name: Deploy to REG.RU (FTP)

on:
  push:
    branches: [main]

jobs:
  ftp-deploy-ru:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to rusnaturecalendar.ru
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /www/rusnaturecalendar.ru/
          exclude: |
            **/.git*
            **/.git*/**
            .github/**

  ftp-deploy-rf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to календарьрусскойприроды.рф
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /www/xn--80aalbcugdegxpcmlaebma4b5nj.xn--p1ai/
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
